server:
  port: 8081
  error:
    include-stacktrace: on_param #url?trace=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        #include: "*"
        include: info, metrics, health

info:
  app: Spring Boot 2 Essentials
  website: https://google.com.br
