server:
  port: 8081
  error:
    include-stacktrace: on_param #url?trace=true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
